// Pakistan cities - alphabetically sorted for dropdown
export const PAKISTAN_CITIES = [
  'Abbottabad',
  'Adda Jadeed',
  'Ahmedpur East',
  'Arifwala',
  'Attock',
  'Badin',
  'Bahawalnagar',
  'Bahawalpur',
  'Bannu',
  'Bhakkar',
  'Bhalwal',
  'Burewala',
  'Chakwal',
  'Chaman',
  'Charsadda',
  'Chiniot',
  'Chishtian',
  'Chunian',
  'Dadu',
  'Daska',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Faisalabad',
  'Ferozewala',
  'Ghotki',
  'Gojra',
  'Gujranwala',
  'Gujrat',
  'Gwadar',
  'Hafizabad',
  'Haroonabad',
  'Hasilpur',
  'Havelian',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jahanian',
  'Jalalpur',
  'Jaranwala',
  'Jatoi',
  'Jhelum',
  'Kamber',
  'Kamoke',
  'Kamra',
  'Karachi',
  'Kasur',
  'Khairpur',
  'Khanewal',
  'Khanpur',
  'Kharian',
  'Khushab',
  'Kohat',
  'Kot Adu',
  'Kotri',
  'Lahore',
  'Larkana',
  'Layyah',
  'Lodhran',
  'Loralai',
  'Mandi Bahauddin',
  'Mansehra',
  'Mardan',
  'Matiari',
  'Mianwali',
  'Mingora',
  'Mirpur Khas',
  'Mirpur',
  'Multan',
  'Muridke',
  'Muzaffarabad',
  'Muzaffargarh',
  'Nankana Sahib',
  'Narowal',
  'Naushahro Feroze',
  'Nawabshah',
  'Nowshera',
  'Okara',
  'Pakpattan',
  'Peshawar',
  'Quetta',
  'Rahim Yar Khan',
  'Rajanpur',
  'Rawalpindi',
  'Sadiqabad',
  'Sahiwal',
  'Sanghar',
  'Sargodha',
  'Shahdadpur',
  'Sheikhupura',
  'Shikarpur',
  'Sialkot',
  'Sukkur',
  'Swabi',
  'Tando Adam',
  'Tando Allahyar',
  'Taxila',
  'Tharparkar',
  'Thatta',
  'Toba Tek Singh',
  'Vehari',
  'Wah',
  'Wazirabad',
  'Zhob',
] as const;

export type City = (typeof PAKISTAN_CITIES)[number];

export const CITY_STORAGE_KEY = 'madadgar_city';
